
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;



public class InputFrame extends javax.swing.JFrame {

    /** Creates new form InputFrame */
    public InputFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputLabel = new javax.swing.JLabel();
        inputEditField = new javax.swing.JTextField();
        formatterTypeField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jOpenButton = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        outputEditFIeld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        inputLabel.setText("Input");

        jButton1.setText("Validate / Modify");
        jButton1.setActionCommand("validate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jOpenButton.setText("Open Note");
        jOpenButton.setActionCommand("validate");
        jOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOpenButtonActionPerformed(evt);
            }

        });

        outputLabel.setText("Output");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(inputEditField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                     .addComponent(formatterTypeField, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jOpenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(outputLabel)
                    .addComponent(outputEditFIeld, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(formatterTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addComponent(jOpenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputEditFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//written code--------------------
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //	 DataOutput proxy = new CapitalLetterProxy(new DataValidatedOutput());
    	
    	  String data = inputEditField.getText();
    	  String type = formatterTypeField.getText();
    	  InputAdapter iA = new InputAdapter(data); 
    	  DataOutput proxy =  CapitalizeFactory.createProxy(type);
    	  proxy.setDisplay(outputEditFIeld);
      // DataOutput proxy = new AllToUpperProxy(new DataValidatedOutput(outputEditFIeld));
        try {
           proxy.showData(data);
        	proxy.parseData(iA.formatData());
        } catch (ProxyValidationException ex) {
            System.out.println("Error " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

     private void jOpenButtonActionPerformed(ActionEvent evt) {
                  System.out.println("BTN 2");
                  WriteReadSingleton singleton = WriteReadSingleton.instance();
                  final File FOLDER = new File("C:\\Users\\The_warri0r\\workspace\\mainBodyCourceProj\\Notes\\");
                  ArrayList<String> fileNames = new ArrayList<String>();
                  fileNames = singleton.listFilesForFolder(FOLDER);

                  for (int i = 0; i < fileNames.size(); i++) {
                    singleton.readFiles("C:\\Users\\The_warri0r\\workspace\\mainBodyCourceProj\\Notes\\" + fileNames.get(i));
                  }
                  
                  sortProxyInterface proxy = new sortProxy();
                  proxy.sortByTitle(singleton.noteData);
//                  
//                  for (int i = 0; i < singleton.noteData.size(); i++) {
//					 System.out.println(singleton.noteData.get(i).getNoteTitle());
//                  }
                  
            }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputEditField;
    private javax.swing.JTextField formatterTypeField;
    private javax.swing.JLabel inputLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jOpenButton;
    private javax.swing.JTextField outputEditFIeld;
    private javax.swing.JLabel outputLabel;
    // End of variables declaration//GEN-END:variables

}
